#Mount Google Drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

#Load 17 Molecular Properties of COVID-19 Drugs

In [ ]:
path = "/content/drive/MyDrive/17moleculeCovid19DrugProperties.csv"
import csv
import pandas as pd
df = pd.read_csv(path)
df

,Unnamed: 0,PubChemID,Molecular_Weight,XLogp,Hydrogen_Bond_Donor_Count,Hydrogen_Bond_Acceptor_Count,Rotatable_Bond_Count,Exact_Mass,Monoisotopic_Mass,Topological_Polar_Surface_Area,Heavy_Atom_Count,Formal_Charge,Complexity,Isotope_Atom_Count,Defined_Atom_Stereocenter_Count,Undefined_Atom_Stereocenter_Count,Defined_Bond_Stereocenter_Count,Undefined_Bond_Stereocenter_Count,Covalently_Bonded_Unit_Count
0,0,121304016,602.60,1.9,4,13,14,602.225399,602.225399,204.0,42,0,1010,0,6,0,0,0,1
1,1,131411,477.40,4.4,1,5,8,476.076930,476.076930,80.0,29,0,546,0,0,0,0,0,1
2,2,134223875,407.50,4.1,2,6,5,407.173273,407.173273,87.1,30,0,869,0,1,0,0,0,1
3,3,135626798,420.50,2.9,1,4,9,420.216141,420.216141,74.2,31,0,661,0,0,0,0,0,1
4,4,155903259,499.50,2.2,3,8,7,499.240639,499.240639,131.0,35,0,964,0,6,0,0,0,1
5,5,6741,374.50,1.9,3,5,2,374.209324,374.209324,94.8,27,0,754,0,8,0,0,0,1
6,6,92727,628.80,5.9,4,5,15,628.362471,628.362471,120.0,46,0,940,0,4,0,0,0,1
7,7,392622,720.90,6.0,4,9,18,720.312761,720.312761,202.0,50,0,1040,0,4,0,0,0,1
8,8,145996610,329.31,-0.8,4,7,6,329.122300,329.122300,141.0,23,0,534,0,4,0,0,0,1
9,9,6321424,875.10,4.1,3,14,8,874.507857,874.507857,170.0,62,0,1680,0,20,0,3,0,1
10,10,492405,157.10,-0.6,2,4,1,157.028755,157.028755,84.6,11,0,282,0,0,0,0,0,1
11,11,3652,335.90,3.6,2,4,9,335.176440,335.176440,48.4,23,0,331,0,0,1,0,0,1
12,12,447043,749.00,4.0,5,14,7,748.508526,748.508526,180.0,52,0,1150,0,18,0,0,0,1
13,13,5324346,318.33,2.6,1,7,9,318.155512,318.155512,56.8,22,0,327,0,0,0,1,0,1
14,14,5743,392.50,1.9,3,6,2,392.199902,392.199902,94.8,28,0,805,0,8,0,0,0,1
15,15,44205240,371.40,-0.5,1,7,5,371.116444,371.116444,129.0,26,0,678,0,0,0,0,0,1
16,16,64927,515.90,NaN,7,11,8,515.135317,515.135317,184.0,32,0,359,0,0,1,0,0,3
17,17,46215462,506.60,5.5,2,7,4,506.290643,506.290643,97.8,38,0,775,0,1,0,0,0,1
18,18,12947,434.00,NaN,4,8,9,433.143820,433.143820,131.0,28,0,413,0,0,1,0,0,2
19,19,132274054,383.40,0.4,3,7,3,383.105211,383.105211,129.0,27,0,754,0,0,0,1,0,1

In [ ]:
#df.fillna(df.mean())
df.isna().any()
df=df.fillna(0)
#X=X.drop(columns=['XLogp'])

In [ ]:
df.drop(df.columns[[0]], axis=1, inplace=True)
df

,PubChemID,Molecular_Weight,XLogp,Hydrogen_Bond_Donor_Count,Hydrogen_Bond_Acceptor_Count,Rotatable_Bond_Count,Exact_Mass,Monoisotopic_Mass,Topological_Polar_Surface_Area,Heavy_Atom_Count,Formal_Charge,Complexity,Isotope_Atom_Count,Defined_Atom_Stereocenter_Count,Undefined_Atom_Stereocenter_Count,Defined_Bond_Stereocenter_Count,Undefined_Bond_Stereocenter_Count,Covalently_Bonded_Unit_Count
0,121304016,602.60,1.9,4,13,14,602.225399,602.225399,204.0,42,0,1010,0,6,0,0,0,1
1,131411,477.40,4.4,1,5,8,476.076930,476.076930,80.0,29,0,546,0,0,0,0,0,1
2,134223875,407.50,4.1,2,6,5,407.173273,407.173273,87.1,30,0,869,0,1,0,0,0,1
3,135626798,420.50,2.9,1,4,9,420.216141,420.216141,74.2,31,0,661,0,0,0,0,0,1
4,155903259,499.50,2.2,3,8,7,499.240639,499.240639,131.0,35,0,964,0,6,0,0,0,1
5,6741,374.50,1.9,3,5,2,374.209324,374.209324,94.8,27,0,754,0,8,0,0,0,1
6,92727,628.80,5.9,4,5,15,628.362471,628.362471,120.0,46,0,940,0,4,0,0,0,1
7,392622,720.90,6.0,4,9,18,720.312761,720.312761,202.0,50,0,1040,0,4,0,0,0,1
8,145996610,329.31,-0.8,4,7,6,329.122300,329.122300,141.0,23,0,534,0,4,0,0,0,1
9,6321424,875.10,4.1,3,14,8,874.507857,874.507857,170.0,62,0,1680,0,20,0,3,0,1
10,492405,157.10,-0.6,2,4,1,157.028755,157.028755,84.6,11,0,282,0,0,0,0,0,1
11,3652,335.90,3.6,2,4,9,335.176440,335.176440,48.4,23,0,331,0,0,1,0,0,1
12,447043,749.00,4.0,5,14,7,748.508526,748.508526,180.0,52,0,1150,0,18,0,0,0,1
13,5324346,318.33,2.6,1,7,9,318.155512,318.155512,56.8,22,0,327,0,0,0,1,0,1
14,5743,392.50,1.9,3,6,2,392.199902,392.199902,94.8,28,0,805,0,8,0,0,0,1
15,44205240,371.40,-0.5,1,7,5,371.116444,371.116444,129.0,26,0,678,0,0,0,0,0,1
16,64927,515.90,0.0,7,11,8,515.135317,515.135317,184.0,32,0,359,0,0,1,0,0,3
17,46215462,506.60,5.5,2,7,4,506.290643,506.290643,97.8,38,0,775,0,1,0,0,0,1
18,12947,434.00,0.0,4,8,9,433.143820,433.143820,131.0,28,0,413,0,0,1,0,0,2
19,132274054,383.40,0.4,3,7,3,383.105211,383.105211,129.0,27,0,754,0,0,0,1,0,1

#Load Side Effects of COVID-19 Drugs

In [ ]:
path = "/content/drive/MyDrive/ADR.csv"
import csv
import pandas as pd
df1 = pd.read_csv(path)
df1

,Drug Name,PubChemID,0,1,2,3,4,5,6,7,...,22,23,24,25,26,27,28,29,30,31
0,Remdesivir,121304016,0,0,1,1,0,1,1,1,...,1,1,0,1,0,1,0,0,1,0
1,Umifenovir,131411,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Protein kinase inhibitors 1,132274054,0,0,0,0,0,0,0,0,...,0,0,1,0,1,0,0,0,1,1
3,Zyesami,134223875,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Peginterferon Lambda,135626798,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
5,PF-07321332,155903259,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
6,Methylprednisolone,6741,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
7,Lopinavir,92727,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
8,Ritonavir,392622,0,1,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0
9,MK-4482,145996610,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
10,Ivermectin,6321424,0,1,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,1,0
11,Favipiravir,492405,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
12,Hydroxychloroquine,3652,0,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
13,azithromycin,447043,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
14,Fluvoxamine,5324346,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
15,Dexamethasone,5743,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
16,Baricitinib,44205240,0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
17,Chloroquine phosphate,64927,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
18,Bemcentinib,46215462,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,Hydroxychloroquine sulfate,12947,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [ ]:
df1.drop(df1.columns[[0]], axis=1, inplace=True)
df1

,PubChemID,0,1,2,3,4,5,6,7,8,...,22,23,24,25,26,27,28,29,30,31
0,121304016,0,0,1,1,0,1,1,1,0,...,1,1,0,1,0,1,0,0,1,0
1,131411,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,132274054,0,0,0,0,0,0,0,0,0,...,0,0,1,0,1,0,0,0,1,1
3,134223875,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,135626798,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
5,155903259,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
6,6741,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
7,92727,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
8,392622,0,1,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
9,145996610,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
10,6321424,0,1,0,0,0,0,0,0,1,...,1,1,0,0,0,0,0,0,1,0
11,492405,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
12,3652,0,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
13,447043,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
14,5324346,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
15,5743,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
16,44205240,0,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
17,64927,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
18,46215462,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,12947,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

#Merge 17 Molecules Properties Corresponding to Side Effects of COVID-19 Drugs

In [ ]:
df2=pd.merge(df,df1, left_on="PubChemID", right_on="PubChemID")
df2

,PubChemID,Molecular_Weight,XLogp,Hydrogen_Bond_Donor_Count,Hydrogen_Bond_Acceptor_Count,Rotatable_Bond_Count,Exact_Mass,Monoisotopic_Mass,Topological_Polar_Surface_Area,Heavy_Atom_Count,...,22,23,24,25,26,27,28,29,30,31
0,121304016,602.60,1.9,4,13,14,602.225399,602.225399,204.0,42,...,1,1,0,1,0,1,0,0,1,0
1,131411,477.40,4.4,1,5,8,476.076930,476.076930,80.0,29,...,0,0,0,0,0,0,0,0,0,0
2,134223875,407.50,4.1,2,6,5,407.173273,407.173273,87.1,30,...,0,0,0,0,0,0,0,0,0,0
3,135626798,420.50,2.9,1,4,9,420.216141,420.216141,74.2,31,...,0,0,0,0,1,0,0,0,0,1
4,155903259,499.50,2.2,3,8,7,499.240639,499.240639,131.0,35,...,0,0,0,0,0,0,0,0,1,0
5,6741,374.50,1.9,3,5,2,374.209324,374.209324,94.8,27,...,0,0,0,1,0,0,0,0,1,0
6,92727,628.80,5.9,4,5,15,628.362471,628.362471,120.0,46,...,0,0,0,0,0,0,1,0,1,0
7,392622,720.90,6.0,4,9,18,720.312761,720.312761,202.0,50,...,0,0,0,0,1,0,0,0,1,0
8,145996610,329.31,-0.8,4,7,6,329.122300,329.122300,141.0,23,...,1,0,0,0,0,0,0,0,1,0
9,6321424,875.10,4.1,3,14,8,874.507857,874.507857,170.0,62,...,1,1,0,0,0,0,0,0,1,0
10,492405,157.10,-0.6,2,4,1,157.028755,157.028755,84.6,11,...,0,0,0,0,0,0,0,1,0,0
11,3652,335.90,3.6,2,4,9,335.176440,335.176440,48.4,23,...,1,0,0,0,0,0,0,0,0,0
12,447043,749.00,4.0,5,14,7,748.508526,748.508526,180.0,52,...,0,0,0,0,0,0,1,0,1,0
13,5324346,318.33,2.6,1,7,9,318.155512,318.155512,56.8,22,...,0,0,0,1,0,0,0,0,1,0
14,5743,392.50,1.9,3,6,2,392.199902,392.199902,94.8,28,...,0,0,0,0,0,0,1,0,0,0
15,44205240,371.40,-0.5,1,7,5,371.116444,371.116444,129.0,26,...,0,0,0,0,1,0,0,0,1,0
16,64927,515.90,0.0,7,11,8,515.135317,515.135317,184.0,32,...,0,0,0,0,0,0,0,0,1,0
17,46215462,506.60,5.5,2,7,4,506.290643,506.290643,97.8,38,...,0,0,0,0,0,0,0,0,0,0
18,12947,434.00,0.0,4,8,9,433.143820,433.143820,131.0,28,...,0,0,0,0,0,0,0,0,1,0
19,132274054,383.40,0.4,3,7,3,383.105211,383.105211,129.0,27,...,0,0,1,0,1,0,0,0,1,1

In [ ]:
df2=df2.drop(['PubChemID'], axis = 1)
df2

,Molecular_Weight,XLogp,Hydrogen_Bond_Donor_Count,Hydrogen_Bond_Acceptor_Count,Rotatable_Bond_Count,Exact_Mass,Monoisotopic_Mass,Topological_Polar_Surface_Area,Heavy_Atom_Count,Formal_Charge,...,22,23,24,25,26,27,28,29,30,31
0,602.60,1.9,4,13,14,602.225399,602.225399,204.0,42,0,...,1,1,0,1,0,1,0,0,1,0
1,477.40,4.4,1,5,8,476.076930,476.076930,80.0,29,0,...,0,0,0,0,0,0,0,0,0,0
2,407.50,4.1,2,6,5,407.173273,407.173273,87.1,30,0,...,0,0,0,0,0,0,0,0,0,0
3,420.50,2.9,1,4,9,420.216141,420.216141,74.2,31,0,...,0,0,0,0,1,0,0,0,0,1
4,499.50,2.2,3,8,7,499.240639,499.240639,131.0,35,0,...,0,0,0,0,0,0,0,0,1,0
5,374.50,1.9,3,5,2,374.209324,374.209324,94.8,27,0,...,0,0,0,1,0,0,0,0,1,0
6,628.80,5.9,4,5,15,628.362471,628.362471,120.0,46,0,...,0,0,0,0,0,0,1,0,1,0
7,720.90,6.0,4,9,18,720.312761,720.312761,202.0,50,0,...,0,0,0,0,1,0,0,0,1,0
8,329.31,-0.8,4,7,6,329.122300,329.122300,141.0,23,0,...,1,0,0,0,0,0,0,0,1,0
9,875.10,4.1,3,14,8,874.507857,874.507857,170.0,62,0,...,1,1,0,0,0,0,0,0,1,0
10,157.10,-0.6,2,4,1,157.028755,157.028755,84.6,11,0,...,0,0,0,0,0,0,0,1,0,0
11,335.90,3.6,2,4,9,335.176440,335.176440,48.4,23,0,...,1,0,0,0,0,0,0,0,0,0
12,749.00,4.0,5,14,7,748.508526,748.508526,180.0,52,0,...,0,0,0,0,0,0,1,0,1,0
13,318.33,2.6,1,7,9,318.155512,318.155512,56.8,22,0,...,0,0,0,1,0,0,0,0,1,0
14,392.50,1.9,3,6,2,392.199902,392.199902,94.8,28,0,...,0,0,0,0,0,0,1,0,0,0
15,371.40,-0.5,1,7,5,371.116444,371.116444,129.0,26,0,...,0,0,0,0,1,0,0,0,1,0
16,515.90,0.0,7,11,8,515.135317,515.135317,184.0,32,0,...,0,0,0,0,0,0,0,0,1,0
17,506.60,5.5,2,7,4,506.290643,506.290643,97.8,38,0,...,0,0,0,0,0,0,0,0,0,0
18,434.00,0.0,4,8,9,433.143820,433.143820,131.0,28,0,...,0,0,0,0,0,0,0,0,1,0
19,383.40,0.4,3,7,3,383.105211,383.105211,129.0,27,0,...,0,0,1,0,1,0,0,0,1,1

In [ ]:
import pandas as pd
from IPython.display import display, HTML, Image
import numpy as np
import matplotlib.pyplot as plt
import copy
import random
from sklearn.base import BaseEstimator, ClassifierMixin, clone
from sklearn.utils.validation import check_X_y, check_array, check_is_fitted
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

from sklearn.metrics import make_scorer
from sklearn import metrics

# to avoid future warnings for sklearn
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from sklearn.metrics import confusion_matrix
import sklearn.metrics as skm

#Store 17 molecules properties in the Variable X and Side Effects in the Variable y.

In [ ]:
# split the features-X and class labels-y
X = df2.iloc[:, 0:17]
y = df2.iloc[:, 17:]
y1 = df2.iloc[:, 17:]
print("X.shape: " + str(X.shape))
display(X.head())
print("y.shape: " + str(y.shape))
display(y.head())
print("Descriptive stats:")
X.describe()

X.shape: (20, 17)

,Molecular_Weight,XLogp,Hydrogen_Bond_Donor_Count,Hydrogen_Bond_Acceptor_Count,Rotatable_Bond_Count,Exact_Mass,Monoisotopic_Mass,Topological_Polar_Surface_Area,Heavy_Atom_Count,Formal_Charge,Complexity,Isotope_Atom_Count,Defined_Atom_Stereocenter_Count,Undefined_Atom_Stereocenter_Count,Defined_Bond_Stereocenter_Count,Undefined_Bond_Stereocenter_Count,Covalently_Bonded_Unit_Count
0,602.6,1.9,4,13,14,602.225399,602.225399,204.0,42,0,1010,0,6,0,0,0,1
1,477.4,4.4,1,5,8,476.076930,476.076930,80.0,29,0,546,0,0,0,0,0,1
2,407.5,4.1,2,6,5,407.173273,407.173273,87.1,30,0,869,0,1,0,0,0,1
3,420.5,2.9,1,4,9,420.216141,420.216141,74.2,31,0,661,0,0,0,0,0,1
4,499.5,2.2,3,8,7,499.240639,499.240639,131.0,35,0,964,0,6,0,0,0,1

y.shape: (20, 32)

   0  1  2  3  4  5  6  7  8  9  ...  22  23  24  25  26  27  28  29  30  31
0  0  0  1  1  0  1  1  1  0  1  ...   1   1   0   1   0   1   0   0   1   0
1  0  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   0   0
2  0  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   0   0
3  0  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   1   0   0   0   0   1
4  0  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   1   0

[5 rows x 32 columns]

Descriptive stats:

,Molecular_Weight,XLogp,Hydrogen_Bond_Donor_Count,Hydrogen_Bond_Acceptor_Count,Rotatable_Bond_Count,Exact_Mass,Monoisotopic_Mass,Topological_Polar_Surface_Area,Heavy_Atom_Count,Formal_Charge,Complexity,Isotope_Atom_Count,Defined_Atom_Stereocenter_Count,Undefined_Atom_Stereocenter_Count,Defined_Bond_Stereocenter_Count,Undefined_Bond_Stereocenter_Count,Covalently_Bonded_Unit_Count
count,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.0,20.000000,20.0,20.000000,20.000000,20.00000,20.0,20.00000
mean,475.012000,2.475000,2.950000,7.550000,7.450000,474.565383,474.565383,121.975000,33.100000,0.0,743.600000,0.0,4.000000,0.150000,0.25000,0.0,1.15000
std,170.178575,2.209281,1.538112,3.170173,4.406634,170.079649,170.079649,46.825498,12.086966,0.0,341.579982,0.0,5.866946,0.366348,0.71635,0.0,0.48936
min,157.100000,-0.800000,1.000000,4.000000,1.000000,157.028755,157.028755,48.400000,11.000000,0.0,282.000000,0.0,0.000000,0.000000,0.00000,0.0,1.00000
25%,373.725000,0.300000,2.000000,5.000000,4.750000,373.436104,373.436104,86.475000,26.750000,0.0,503.750000,0.0,0.000000,0.000000,0.00000,0.0,1.00000
50%,427.250000,2.400000,3.000000,7.000000,7.500000,426.679980,426.679980,124.500000,29.500000,0.0,754.000000,0.0,1.000000,0.000000,0.00000,0.0,1.00000
75%,537.575000,4.100000,4.000000,8.250000,9.000000,536.907837,536.907837,148.250000,39.000000,0.0,946.000000,0.0,6.000000,0.000000,0.00000,0.0,1.00000
max,875.100000,6.000000,7.000000,14.000000,18.000000,874.507857,874.507857,204.000000,62.000000,0.0,1680.000000,0.0,20.000000,1.000000,3.00000,0.0,3.00000

#MLSMOTE Code

In [ ]:
import numpy as np
import pandas as pd
import random
from sklearn.datasets import make_classification
from sklearn.neighbors import NearestNeighbors

def get_tail_label(df: pd.DataFrame, ql=[0.05, 1.]) -> list:
    """
    Find the underrepresented targets.
    Underrepresented targets are those which are observed less than the median occurance.
    Targets beyond a quantile limit are filtered.
    """
    irlbl = df.sum(axis=0)
    irlbl = irlbl[(irlbl > irlbl.quantile(ql[0])) & ((irlbl < irlbl.quantile(ql[1])))]  # Filtering
    irlbl = irlbl.max() / irlbl
    threshold_irlbl = irlbl.median()
    tail_label = irlbl[irlbl > threshold_irlbl].index.tolist()
    return tail_label

def get_minority_samples(X: pd.DataFrame, y: pd.DataFrame, ql=[0.05, 1.]):
    """
    return
    X_sub: pandas.DataFrame, the feature vector minority dataframe
    y_sub: pandas.DataFrame, the target vector minority dataframe
    """
    tail_labels = get_tail_label(y, ql=ql)
    index = y[y[tail_labels].apply(lambda x: (x == 1).any(), axis=1)].index.tolist()

    X_sub = X[X.index.isin(index)].reset_index(drop = True)
    y_sub = y[y.index.isin(index)].reset_index(drop = True)
    return X_sub, y_sub

def nearest_neighbour(X: pd.DataFrame, neigh) -> list:
    """
    Give index of 10 nearest neighbor of all the instance

    args
    X: np.array, array whose nearest neighbor has to find

    return
    indices: list of list, index of 5 NN of each element in X
    """
    nbs = NearestNeighbors(n_neighbors=neigh, metric='euclidean', algorithm='kd_tree').fit(X)
    euclidean, indices = nbs.kneighbors(X)
    return indices

def MLSMOTE(X, y, n_sample, neigh=3):
    """
    Give the augmented data using MLSMOTE algorithm

    args
    X: pandas.DataFrame, input vector DataFrame
    y: pandas.DataFrame, feature vector dataframe
    n_sample: int, number of newly generated sample

    return
    new_X: pandas.DataFrame, augmented feature vector data
    target: pandas.DataFrame, augmented target vector data
    """
    indices2 = nearest_neighbour(X, neigh=3)
    n = len(indices2)
    new_X = np.zeros((n_sample, X.shape[1]))
    target = np.zeros((n_sample, y.shape[1]))
    for i in range(n_sample):
        reference = random.randint(0, n-1)
        neighbor = random.choice(indices2[reference, 1:])
        all_point = indices2[reference]
        nn_df = y[y.index.isin(all_point)]
        ser = nn_df.sum(axis = 0, skipna = True)
        target[i] = np.array([1 if val > 0 else 0 for val in ser])
        ratio = random.random()
        gap = X.loc[reference,:] - X.loc[neighbor,:]
        new_X[i] = np.array(X.loc[reference,:] + ratio * gap)
    new_X = pd.DataFrame(new_X, columns=X.columns)
    target = pd.DataFrame(target, columns=y.columns)
    return new_X, target

X_sub, y_sub = get_minority_samples(X, y)  # Getting minority samples of that datframe
X_res, y_res = MLSMOTE(X_sub, y_sub, 280, 32)  # Applying MLSMOTE to augment the dataframe
X = pd.concat([X, X_res])
y = pd.concat([y, y_res])
y1=y

#Accuracy Function for Multi-Level Classification

In [ ]:

from sklearn.datasets import make_circles
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import confusion_matrix

def main_accuracy_score(y_test, y_pred):
    # y_pred is a numpy array, y_test is a dataframe
    # to compare the two, convert to a single type
    y_test = y_test.to_numpy()

    # shape of test and preds must be equal
    assert y_test.shape == y_pred.shape
    i=0
    # list of scores for each training sample
    scores = []

    # for each test sample
    while i < len(y_test):
        count=0
        # count the number of matches in the sample
        # y_test[i] -> row values in test set (true values)
        # y_pred[i] -> row values in predictions set (predicted values)
        for p, q in zip(y_test[i], y_pred[i]):
            if p == q:
                count += 1

        # accuracy score for the sample = no. of correctly predicted labels/total no. of labels
        scores.append(count / y_pred.shape[1])
        i+=1

    # final accuracy = avg. accuracy over all test samples =
    # sum of the accuracy of all training samples/no. of training samples
    return round((sum(scores)/len(y_test)), 5)

In [ ]:
def plot(conf_matrix, labels):
    plot_count = 1
    fig = plt.figure(figsize=(20, 60))
    for _ in range(len(labels)//4):
        plt.subplot(len(labels), 4, plot_count)
        sns.heatmap(conf_matrix[labels[plot_count-1]], annot=True, fmt='g')
        plt.title(f'{labels[plot_count-1]} Confusion Matrix')
        plot_count += 1

        plt.subplot(len(labels), 4, plot_count)
        sns.heatmap(conf_matrix[labels[plot_count-1]], annot=True, fmt='g')
        plt.title(f'{labels[plot_count-1]} Confusion Matrix')
        plot_count += 1

        plt.subplot(len(labels), 4, plot_count)
        sns.heatmap(conf_matrix[labels[plot_count-1]], annot=True, fmt='g')
        plt.title(f'{labels[plot_count-1]} Confusion Matrix')
        plot_count += 1

        plt.subplot(len(labels), 4, plot_count)
        sns.heatmap(conf_matrix[labels[plot_count-1]], annot=True, fmt='g')
        plt.title(f'{labels[plot_count-1]} Confusion Matrix')
        plot_count += 1

In [ ]:
X=X.to_numpy()
y=y.to_numpy()

#Import Leave-One-Out Cross-Validation Package for Training and Testing the Model.

In [ ]:
from sklearn.model_selection import LeaveOneOut
loo = LeaveOneOut()
loo.get_n_splits(X)

300

In [ ]:
pip install scikit-multilearn

Collecting scikit-multilearn
  Downloading scikit_multilearn-0.2.0-py3-none-any.whl.metadata (6.0 kB)
Downloading scikit_multilearn-0.2.0-py3-none-any.whl (89 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.4/89.4 kB 2.4 MB/s eta 0:00:00
Installing collected packages: scikit-multilearn
Successfully installed scikit-multilearn-0.2.0

#Code to Choose the First 𝐾1 Drug Neighbors and Assign the Maximum Side Effects Class of 𝐾1 to the Test Drug Sample using K Nearest Neighbour.

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest, f_classif


class BestKNN:
    def __init__(self, distance_metric='euclidean'):
        self.distance_metric = distance_metric
        self.scaler = StandardScaler()
        self.knn_classifier = KNeighborsClassifier(metric=distance_metric)

    def fit(self, X_train, y_train):
        # Perform feature scaling on the training data
        self.scaler.fit(X_train)
        X_train_scaled = self.scaler.transform(X_train)
        # Fit KNN classifier on the scaled data
        self.knn_classifier.fit(X_train_scaled, y_train)

    def predict(self, X_test):
        # Scale the test data using the same scaler
        X_test_scaled = self.scaler.transform(X_test)
        # Predict using the trained KNN classifier
        return self.knn_classifier.predict(X_test_scaled)

    def find_optimal_params(self, X_train, y_train):
        param_grid = {
            'n_neighbors': range(3, 21, 2),  # Ensuring k values are odd
            'weights': ['uniform', 'distance']
        }
        grid_search = GridSearchCV(self.knn_classifier, param_grid, cv=5, scoring='accuracy')
        grid_search.fit(X_train, y_train)
        return grid_search.best_params_, grid_search.best_estimator_

In [ ]:
from skmultilearn.problem_transform import BinaryRelevance
from scipy.sparse import csr_matrix
from scipy import sparse
import array
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import NearestNeighbors
from sklearn.metrics import hamming_loss
import numpy as np
from sklearn.metrics import accuracy_score
import numpy as np
from sklearn.metrics import confusion_matrix

from sklearn.metrics import classification_report

stdma=[]
stdhl=[]
stdsa=[]
stdp=[]
stdr=[]
stdf=[]
stdroc=[]
y_pred2=[]
i=0
for train_index, test_index in loo.split(X):
    #print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    #print(X_train, X_test, y_train, y_test)

    #print("Training on Fold: ",i+1)
    #X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.2, random_state = np.random.randint(1,1000, 1)[0])
    clf = BestKNN()
    optimal_params, best_estimator = clf.find_optimal_params(X_train, y_train)
    print("Optimal hyperparameters:", optimal_params)

    # Display the optimal value of k
    print("Optimal value of k:", optimal_params['n_neighbors'])

    clf = BinaryRelevance(BestKNN(), require_dense=True)
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    y_pred = y_pred.todense()
    y_pred1 = y_pred.ravel()
    y_pred1=pd.DataFrame(y_pred1)
    y_pred1=y_pred1.astype(int)
    y_pred1=y_pred1.to_numpy()
    # predict
    y_pred2.append(y_pred1)

Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 5, 'weights': 'uniform'}
Optimal value of k: 5
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 5, 'weights': 'uniform'}
Optimal value of k: 5
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 5, 'weights': 'uniform'}
Optimal value of k: 5
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3
Optimal hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Optimal value of k: 3

In [ ]:
store=pd.DataFrame(np.concatenate(y_pred2))
store

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,0,1,1,1,0,1,1,1,0,1,...,1,1,0,1,0,1,1,0,1,0
1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,1,1,0,0,0,1,1
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
3,0,1,0,0,0,0,0,0,0,0,...,0,0,0,1,1,0,0,0,1,1
4,0,0,0,0,0,0,0,0,0,0,...,0,0,1,1,1,0,1,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,0,1,1,1,0,1,1,1,1,1,...,1,1,0,1,0,1,1,0,1,0
296,0,1,1,1,0,1,1,1,0,1,...,1,1,0,1,0,1,1,0,1,0
297,0,0,0,0,0,0,0,0,0,0,...,0,0,1,1,1,0,1,0,1,1
298,0,1,0,0,0,0,0,0,1,0,...,0,0,0,1,1,0,0,1,1,0
299,0,0,0,0,0,0,0,0,0,0,...,0,0,1,1,1,0,1,0,1,1

#Code for the Calculation of Side Effects Co-occurrence and SE-SE Similarity, and Choosing the Most K2 Similar Side Effects Assigned by K1, then Labeling Them to the Test Drug.

In [ ]:
path = "/content/drive/MyDrive/ADR.csv"
df1 = pd.read_csv(path)
df1=df1.drop([2])
y = df1.iloc[:, 2:]
df_asint = y.astype(int)
cooccc = df_asint.T.dot(df_asint)
np.fill_diagonal(cooccc.values,0)


from scipy.spatial.distance import squareform, pdist
import numpy as np
def SE_SE_Similarity(inputdataset,k):
    dist1 = pdist(inputdataset, metric="jaccard")
    s_dist1 = squareform(dist1)
    sim1 = np.subtract(1, s_dist1)
    sim_df1 = pd.DataFrame(sim1, columns=inputdataset.index, index=inputdataset.index)
    df_adr = pd.DataFrame()
    df_adrknn = []
    df_adrdistance=[]
    labeladr=32
    A1=0
    for i in range(labeladr):
        a1 = sim_df1[A1:A1+1]
        a1 = a1.values.tolist()
        new_data_point1 = np.array(a1)

        distancesadr = np.linalg.norm(sim_df1 - new_data_point1, axis=1)
        #df.append(c)
        #print(distancesadr)
        k = k
        nearest_neighbor_adr = distancesadr.argsort()[:k]
        df_adrdistance.append(distancesadr)
        df_adrknn.append(nearest_neighbor_adr)
        #print(df_adrknn)
        A1=A1+1

    dfadrknn = pd.DataFrame(df_adrknn)
    dfadrknn.drop(dfadrknn.columns[[0]], axis=1, inplace=True)
    return(dfadrknn)
dfadrknn=SE_SE_Similarity(cooccc,8)  #The value 8 represents the value of k2+1, where a sample is similar with itself. Later, the self-similarity is removed in the following next code block line: a = a.iloc[:, 1:].

In [ ]:
for j, row in store.iterrows():
    a=[]
    for i in store.columns:
        newDf = store.loc[lambda df: df[i] == 1]
        if(not newDf.empty):
            a.append(i)
    alistforneighbor=a

    a = pd.DataFrame({'RowId':a})
    a=a.join(dfadrknn, how='inner')
    a=a.iloc[:,1:]  # Selects all rows from the DataFrame a, but excludes the first column (the first column contains the self-similarity score).

    alistforneighboradr=a.index.values.tolist()
    alistforneighboradr

    for i in alistforneighboradr:
        store.iloc[0,a.iloc[i].values] = 1
    store

In [ ]:
for j, row in store.iterrows():
    a=[]
    for i in store.columns:
        newDf = store.loc[lambda df: df[i] == 1]
        if(not newDf.empty):
            a.append(i)
    alistforneighbor=a

    a = pd.DataFrame({'RowId':a})
    a=a.join(dfadrknn, how='inner')
    a=a.iloc[:,1:]

    alistforneighboradr=a.index.values.tolist()
    alistforneighboradr

    for i in alistforneighboradr:
        store.iloc[0,a.iloc[i].values] = 1
    store

In [ ]:
side_effet_pred=store
side_effet_pred=np.array(store, dtype=int)
side_effet_pred

array([[1, 1, 1, ..., 1, 1, 1],
       [0, 1, 0, ..., 0, 1, 1],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 0, 1, 1],
       [0, 1, 0, ..., 1, 1, 0],
       [0, 0, 0, ..., 0, 1, 1]])

#Results of Classifier

In [ ]:
y_pred=side_effet_pred
y_test=np.array(y1, dtype=int)

In [ ]:
import numpy as np
from sklearn.metrics import hamming_loss, roc_auc_score, average_precision_score, f1_score

# ----- Example Data (Replace these with your actual y_test and y_pred) -----
# Each row represents one sample and each column represents one label.
# -----------------------------------------------------------------------------

n_samples, n_labels = y_test.shape

# Initialize lists for per-sample metrics (in percentage)
sample_accuracies = []
sample_precisions = []
sample_recalls = []
sample_f1s = []
sample_hamming_losses = []

for i in range(n_samples):
    true_labels = y_test[i]
    pred_labels = y_pred[i]

    # Accuracy: fraction of labels correctly predicted (as percentage)
    acc = round(np.mean(true_labels == pred_labels) * 100)
    sample_accuracies.append(acc)

    # Hamming Loss per sample: fraction of labels misclassified (as percentage)
    sample_hl = round((np.sum(true_labels != pred_labels) / n_labels) * 100)
    sample_hamming_losses.append(sample_hl)

    # Count true positives, predicted positives, and actual positives
    tp = np.sum((true_labels == 1) & (pred_labels == 1))
    pred_pos = np.sum(pred_labels == 1)
    actual_pos = np.sum(true_labels == 1)

    # Precision calculation (handle division by zero)
    if pred_pos == 0:
        precision = 100 if actual_pos == 0 else 0
    else:
        precision = (tp / pred_pos) * 100

    # Recall calculation (handle division by zero)
    if actual_pos == 0:
        recall = 100
    else:
        recall = (tp / actual_pos) * 100

    sample_precisions.append(round(precision))
    sample_recalls.append(round(recall))

    # F1 score: harmonic mean of precision and recall (in percentage)
    if (precision + recall) == 0:
        f1 = 0
    else:
        # Compute F1 from fraction values, then convert to percentage.
        f1 = 2 * ((precision/100) * (recall/100)) / ((precision/100) + (recall/100)) * 100
    sample_f1s.append(round(f1))

# Calculate average metrics across all samples
average_accuracy = round(np.mean(sample_accuracies), 2)
average_precision = round(np.mean(sample_precisions), 2)
average_recall = round(np.mean(sample_recalls), 2)

# Overall Metrics:
overall_hamming = hamming_loss(y_test, y_pred) * 100  # overall Hamming loss in percentage

# For ROC AUC and AUPRC, using hard predictions may be less ideal.
try:
    overall_roc_auc = roc_auc_score(y_test, y_pred, average='micro')
except Exception:
    overall_roc_auc = None

try:
    overall_auprc = average_precision_score(y_test, y_pred, average='micro')
except Exception:
    overall_auprc = None

overall_f1 = f1_score(y_test, y_pred, average='samples', zero_division=0) * 100

# Print per-sample metrics with captions (comma-separated values)
print("accuracy = " + str(sample_accuracies))
print("precision = " + str(sample_precisions))
print("recall = " + str(sample_recalls))
print("f1 = " + str(sample_f1s))
print("hamming_loss = " + str(sample_hamming_losses))

# Print average metrics across samples



#print("\naverage_accuracy = " + str(average_accuracy) + "%")
#print("average_precision = " + str(average_precision) + "%")
#print("average_recall = " + str(average_recall) + "%")

# Print overall metrics with captions
#print("\nOverall Metrics:")
#print(f"Hamming Loss (overall) = {overall_hamming:.2f}%")
#if overall_roc_auc is not None:
#    print(f"ROC AUC (micro-average) = {overall_roc_auc:.4f}")
#else:
#    print("ROC AUC could not be computed (use probability scores).")
#if overall_auprc is not None:
#    print(f"AUPRC (micro-average) = {overall_auprc:.4f}")
#else:
#    print("AUPRC could not be computed (use probability scores).")
#print(f"F1 Score (samples-average) = {overall_f1:.2f}%")

accuracy = [53, 66, 84, 84, 69, 84, 50, 38, 69, 62, 78, 59, 50, 78, 78, 84, 94, 88, 97, 84, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100]
precision = [52, 9, 50, 55, 18, 55, 24, 19, 27, 48, 46, 15, 24, 46, 36, 55, 83, 33, 100, 55, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100]
recall = [100, 50, 60, 100, 67, 100, 100, 57, 60, 100, 100, 50, 100, 100, 100, 100, 83, 100, 80, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100]
f1 = [68, 15, 55, 71, 29, 71, 38, 29, 37, 65, 63, 24, 38, 63, 53, 71, 83, 50, 89, 71, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100]
hamming_loss = [47, 34, 16, 16, 31, 16, 50, 62, 31, 38, 22, 41, 50, 22, 22, 16, 6, 12, 3, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]